
name: Run `autopkg run`
on: [push, pull_request]
jobs:
  autopkg_run:
    name: Install and configure AutoPkg
    runs-on: macos-latest
    steps:
      - name: Install AutoPkg (latest)
        run: |
          AUTOPKG_LATEST=$(curl https://api.github.com/repos/autopkg/autopkg/releases/latest | jq -r '.["assets"][0]["browser_download_url"]')
          curl -LOJs "${AUTOPKG_LATEST}"
          sudo installer -pkg $(basename "${AUTOPKG_LATEST}") -target /
      - name: Configure AutoPkg
        run: |
          AUTOPKG_DIR="/usr/local/autopkg"
          sudo mkdir -p "${AUTOPKG_DIR}"
          sudo chown root:admin "${AUTOPKG_DIR}"
          sudo chmod 775 "${AUTOPKG_DIR}"

          # Configure AutoPkg override directory to be server wide (multi-user)
          RECIPE_OVERRIDE_DIRS="${AUTOPKG_DIR}/recipe_overrides"
          mkdir -p "${RECIPE_OVERRIDE_DIRS}"
          defaults write com.github.autopkg RECIPE_OVERRIDE_DIRS "${RECIPE_OVERRIDE_DIRS}"
          defaults read com.github.autopkg RECIPE_OVERRIDE_DIRS

          # Configure AutoPkg cache dir to be on the data volume
          CACHE_DIR="${AUTOPKG_DIR}/cache"
          mkdir -p "${CACHE_DIR}"
          defaults write com.github.autopkg CACHE_DIR "${CACHE_DIR}"
          defaults read com.github.autopkg CACHE_DIR

          # Configure AutoPkg recipe repo dir to be on the data volume
          RECIPE_REPO_DIR="${AUTOPKG_DIR}/recipe_repos"
          mkdir -p "${RECIPE_REPO_DIR}"
          defaults write com.github.autopkg RECIPE_REPO_DIR "${RECIPE_REPO_DIR}"
          defaults read com.github.autopkg RECIPE_REPO_DIR

          autopkg repo-add https://github.com/autopkg/recipes.git
          autopkg repo-add https://github.com/autopkg/n8felton-recipes.git
      - uses: actions/checkout@v2
      - name: Get changed files
        id: files
        uses: jitterbit/get-changed-files@v1
      - name: Run AutoPkg for changed recipes
        run: |
          for changed_file in ${{ steps.files.outputs.all }}; do
            case "${changed_file}" in
              *.recipe)
                autopkg run -vvvv ${changed_file}
                ;;
              *)
                ;;
            esac
          done
