
name: Run `autopkg run`
on: [push, pull_request]
jobs:
  autopkg_run:
    name: Run `autopkg run`
    runs-on: macos-latest
    steps:
      - uses: jitterbit/get-changed-files@v1
      - name: `autopkg run` on changed files
        run: |
          for changed_file in ${{ steps.files.outputs.all }}; do
            echo "autopkg run -vvvv ${changed_file}"
          done