
name: Run `autopkg run`
on: [push, pull_request]
jobs:
  autopkg_run:
    name: Run `autopkg run`
    runs-on: macos-latest
    steps:
      - name: autopkg run on changed files
      - id: files
        uses: jitterbit/get-changed-files@v1
      - run: |
          for changed_file in ${{ steps.files.outputs.all }}; do
            echo "autopkg run -vvvv ${changed_file}"
          done